const assignments = [
  {
    id: 1,
    title: "Chapter 1 | Classes & Objects",
    questions: [
      { id:1, text:"A ______ is a template (blueprint) for objects.", options:["Object","Class","Method","Fields"], correct:1, translate:"______ هو قالب (مخطط) للكائنات.", explain:"الـ Class هو المخطط أو القالب الذي يتم من خلاله إنشاء الكائنات." },
      { id:2, text:"The set of operations that the object can perform.", options:["Class","Fields","Data","Behavior"], correct:3, translate:"مجموعة العمليات التي يمكن للكائن تنفيذها.", explain:"Behavior = السلوك = العمليات التي يمكن للكائن تنفيذها." },
      { id:3, text:"Which of the following represents attributes?", options:["Properties","Methods","Actions","Functions"], correct:0, translate:"أي مما يلي يمثل السمات؟", explain:"السمات تمثل حالة الكائن، وتُعرف بالـ Properties أو Fields." },
      { id:4, text:"Is this code Correct?<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>class</span> <span class='type'>Game</span> () { }</div></div></div></div>", options:["Yes","No"], correct:1, translate:"هل هذا الكود صحيح؟", explain:"خطأ؛ لا توضع أقواس بعد اسم الكلاس. الصحيح: class Game { }" },
      { id:5, text:"OOP organizes a program as a collection of", options:["set of objects and their interactions","set of modules or functions","set actions and operations","set of data and attributes"], correct:0, translate:"OOP تنظم البرنامج كمجموعة من", explain:"OOP = مجموعة كائنات متفاعلة." },
      { id:6, text:"In OOP, any entity that has both a state and a behavior is called a(n)", options:["class","object","function","method"], correct:1, translate:"في OOP، أي كيان له حالة وسلوك يسمى", explain:"الكائن (Object) هو الكيان الذي له حالة وسلوك." },
      { id:7, text:"The behavior of an object refers to", options:["current values stored in fields","set of operations it can perform","class from which it was created","amount of memory it occupies"], correct:1, translate:"سلوك الكائن يشير إلى", explain:"السلوك = مجموعة العمليات التي يمكن للكائن تنفيذها." },
      { id:8, text:"In OOP, a class serves as a ______ from which objects are created.", options:["method","variable","blueprint (template)","function"], correct:2, translate:"الكلاس يعمل كـ ______ يتم من خلاله إنشاء الكائنات.", explain:"الكلاس = مخطط (Blueprint) لإنشاء الكائنات." },
      { id:9, text:"Data members describing characteristics are called ______, functions defining actions are called ______.", options:["methods, fields","fields, methods","classes, objects","properties, indexes"], correct:1, translate:"أعضاء البيانات تسمى ______، والدوال التي تحدد الأفعال تسمى ______.", explain:"Fields = بيانات، Methods = سلوك." },
      { id:10, text:"To create a class we use keyword", options:["class","new","create","object"], correct:0, translate:"لإنشاء كلاس نستخدم", explain:"class" },
      { id:11, text:"To create a new object we use keyword", options:["class","new","create","object"], correct:1, translate:"لإنشاء كائن جديد نستخدم", explain:"new" },
      { id:12, text:"In memory layout, ______ section holds compiled instructions.", options:["Data","Text","Stack","Heap"], correct:1, translate:"قسم ______ يحمل التعليمات المجمعة (الكود القابل للتنفيذ).", explain:"Text section (أو Code) يخزن تعليمات البرنامج." },
      { id:13, text:"Global and static variables are stored in ______ section.", options:["Data","Text","Stack","Heap"], correct:0, translate:"المتغيرات العامة والثابتة تُخزن في قسم", explain:"Data section" },
      { id:14, text:"Local variables and function call info are stored in ______.", options:["Data","Text","Stack","Heap"], correct:2, translate:"المتغيرات المحلية ومعلومات استدعاء الدوال تُخزن في", explain:"Stack" },
      { id:15, text:"Dynamically allocated memory (objects, arrays) is drawn from ______.", options:["Data","Text","Stack","Heap"], correct:3, translate:"الذاكرة المخصصة ديناميكيًا (كائنات، مصفوفات) تؤخذ من", explain:"Heap" },
      { id:16, text:"Entity which holds actual data is called", options:["Class","Object","Blueprint","Method"], correct:1, translate:"الكيان الذي يحمل البيانات الفعلية يسمى", explain:"Object" },
      { id:17, text:"Multiple classes can be created from a single object.", options:["True","False"], correct:1, translate:"يمكن إنشاء عدة كلاسات من كائن واحد.", explain:"العكس: يمكن إنشاء عدة كائنات من كلاس واحد." },
      { id:18, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>static</span> <span class='type'>int</span>[] arr = <span class='keyword'>new</span> <span class='type'>int</span>[10];</div></div></div></div> Where is arr stored?", options:["Stack","Heap","Text","Data"], correct:3, translate:"أين تُخزن arr؟", explain:"Static variables تُخزن في Data section." },
      { id:19, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>int</span>[] arr = <span class='keyword'>new</span> <span class='type'>int</span>[10];</div></div></div></div> Where is arr stored?", options:["Stack","Heap","Text","Data"], correct:0, translate:"أين تُخزن arr؟", explain:"Local variable arr (reference) stored in Stack." },
      { id:20, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Car</span> c1 = <span class='keyword'>new</span> Car;</div></div></div></div> Correct?", options:["True","False"], correct:1, translate:"هل الكود صحيح؟", explain:"خطأ، الصحيح: Car c1 = new Car();" },
      { id:21, text:"You can create only one object from a given class.", options:["True","False"], correct:1, translate:"يمكن إنشاء كائن واحد فقط من كلاس معين.", explain:"يمكن إنشاء عدد غير محدود من الكائنات." },
      { id:22, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>int</span>[] arr = {5,6,7,8};</div></div></div></div> What does arr contain?", options:["Address of array","5,6,7,8","null","empty"], correct:0, translate:"ماذا يحتوي arr؟", explain:"arr يحتوي على عنوان (مرجع) المصفوفة في Heap." }
    ]
  },
  {
    id: 2,
    title: "Chapter 2 | Class Members",
    questions: [
      { id:1, text:"What is output?<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>static</span> <span class='keyword'>class</span> <span class='type'>student</span> {</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>    <span class='keyword'>public</span> <span class='keyword'>static</span> <span class='type'>int</span> counter = 1;</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>    <span class='keyword'>public</span> student() { counter++; }</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>}</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'><span class='keyword'>static</span> <span class='keyword'>void</span> <span class='function'>Main</span>() {</div></div><div class='code-line'><span class='line-number'>6</span><div class='code'>    Console.WriteLine(student.counter);</div></div><div class='code-line'><span class='line-number'>7</span><div class='code'>}</div></div></div></div>", options:["0","1","2","error"], correct:3, translate:"ما هو الناتج؟", explain:"خطأ: الكلاس الـ static لا يمكن أن يحتوي على Constructor غير static." },
      { id:2, text:"To access the members of a class through an object, you use the ______ syntax", options:[".",":",":","~"], correct:0, translate:"للوصول إلى أعضاء الكلاس عن طريق الكائن، نستخدم علامة ______", explain:"Dot operator (.) تستخدم للوصول إلى الأعضاء." },
      { id:3, text:"The default access level for members of a class is", options:["public","private","internal","protected"], correct:1, translate:"مستوى الوصول الافتراضي لأعضاء الكلاس هو", explain:"private هو المستوى الافتراضي." },
      { id:4, text:"To allow controlled access to private fields from outside, the class typically provides", options:["base class access","protected scope","public accessor methods (getters/setters)","static accessors"], correct:2, translate:"للسماح بالوصول المتحكم به للحقول الخاصة من خارج الكلاس، يوفر الكلاس عادةً", explain:"Getters and setters (Properties) تسمح بالوصول المتحكم." },
      { id:5, text:"Which keyword controls the visibility of a class member?", options:["static","public","visible","base"], correct:1, translate:"أي keyword يتحكم في رؤية عضو الكلاس؟", explain:"public, private, protected, internal" },
      { id:6, text:"The values of fields of a given object represent its", options:["behavior","methods","state","function"], correct:2, translate:"قيم الحقول لكائن معين تمثل", explain:"State = حالة الكائن." },
      { id:7, text:"The methods of a class define how an object of that class", options:["is created","behaves","is destroyed","is stored in memory"], correct:1, translate:"دوال الكلاس تحدد كيف أن الكائن", explain:"Methods = السلوك." },
      { id:8, text:"Which keyword declares a member that belongs to the class itself rather than to any instance?", options:["public","private","static","protected"], correct:2, translate:"أي keyword يصرح بعضو يتبع الكلاس نفسه بدلاً من أي instance؟", explain:"static" },
      { id:9, text:"Which correctly describes a static class?", options:["It can contain non-static members","It contains only static members and cannot be instantiated","It can be instantiated using new","It must inherit from a base class"], correct:1, translate:"أي عبارة تصف static class بشكل صحيح؟", explain:"Static class: all members static, cannot be instantiated." },
      { id:10, text:"Unlike an instance method, a static method belongs to the ______ rather than to any object.", options:["program","class","object","process"], correct:1, translate:"على عكس instance method، الـ static method ينتمي إلى ______ بدلاً من أي كائن.", explain:"الكلاس نفسه." },
      { id:11, text:"A static field exists as", options:["a single shared copy regardless of objects created","a fresh copy for every new object","requires new to initialize","used only in static class"], correct:0, translate:"الحقل الثابت (static field) يوجد كـ", explain:"نسخة واحدة مشتركة بين جميع الكائنات." },
      { id:12, text:"A static method is invoked through the ______ itself.", options:["class name","object name","access modifier","base name"], correct:0, translate:"الـ static method يتم استدعاؤه من خلال ______ نفسه.", explain:"ClassName.MethodName()" },
      { id:13, text:"A static class can be instantiated", options:["True","False"], correct:1, translate:"الـ static class يمكن إنشاء instance منه", explain:"False" },
      { id:14, text:"A non-static class can have static and non-static members", options:["True","False"], correct:0, translate:"الـ non-static class يمكن أن يحتوي على أعضاء static وغير static", explain:"True" },
      { id:15, text:"A private member can be accessed only", options:["by all classes","within the class it is defined","by derived classes","from main method only"], correct:1, translate:"العضو private يمكن الوصول إليه فقط", explain:"داخل الكلاس نفسه." },
      { id:16, text:"If no access modifier is specified, class members are ______ by default.", options:["Public","Private","Protected","Internal"], correct:1, translate:"إذا لم يتم تحديد access modifier، الأعضاء يكونون ______ افتراضيًا.", explain:"private" },
      { id:17, text:"Encapsulation is primarily used to shield fields from having", options:["invalid data","big values","small values","valid data"], correct:0, translate:"التغليف (Encapsulation) يستخدم بشكل أساسي لحماية الحقول من", explain:"منع البيانات غير الصالحة." },
      { id:18, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>public</span> <span class='type'>int</span> x = 5;</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='keyword'>static</span> <span class='keyword'>void</span> <span class='function'>Main</span>(<span class='type'>string</span>[] args) {</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>    <span class='type'>int</span> y = x + 10;</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>    Console.WriteLine(y);</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'>}</div></div></div></div>", options:["5","10","15","error"], correct:3, translate:"ما الناتج؟", explain:"خطأ: لا يمكن الوصول إلى non-static member من static method." },
      { id:19, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Car</span> c1 = <span class='keyword'>new</span> <span class='type'>Car</span>();</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>c1.speed = 1000;</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'><span class='type'>Car</span> c2 = c1;</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>c2.speed = 2000;</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'><span class='keyword'>class</span> <span class='type'>Car</span> { <span class='keyword'>public</span> <span class='type'>int</span> speed; }</div></div><div class='code-line'><span class='line-number'>6</span><div class='code'>Console.WriteLine(c1.speed);</div></div></div></div>", options:["1000","2000","0","error"], correct:1, translate:"ما قيمة c1.speed؟", explain:"c1 و c2 يشيران لنفس الكائن، تغيير speed يؤثر على الكائن نفسه." },
      { id:20, text:"If a class has 5 static data members and we create 3 objects, the system creates ______ static data values.", options:["5","3","15","0"], correct:0, translate:"إذا كان كلاس يحتوي على 5 أعضاء static وأنشأنا 3 كائنات، النظام ينشئ ______ قيمة static.", explain:"Static members توجد مرة واحدة فقط بغض النظر عن عدد الكائنات." },
      { id:21, text:"If a class has 2 instance data members and we create 3 objects, the system creates ______ data values.", options:["2","3","6","0"], correct:2, translate:"إذا كان كلاس يحتوي على 2 instance members وأنشأنا 3 كائنات، النظام ينشئ ______ قيمة.", explain:"2 × 3 = 6 قيم (كل كائن له نسخته الخاصة)." },
      { id:22, text:"If a class has 2 static fields and 3 instance fields, and you create 2 objects, total variables in memory?", options:["2","3","6","8"], correct:3, translate:"كلاس به 2 static و 3 instance، ننشئ 2 كائن، إجمالي المتغيرات في الذاكرة؟", explain:"Static = 2 (مرة واحدة) + Instance (3 × 2 = 6) = 8" }
    ]
  },
  {
    id: 3,
    title: "Chapter 3 | Constructors & Destructors",
    questions: [
      { id:1, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>student</span> s1 = <span class='keyword'>new</span> <span class='type'>student</span>();</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>Console.WriteLine(s1.id);</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'><span class='keyword'>class</span> <span class='type'>student</span> {</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>    <span class='keyword'>public</span> <span class='type'>int</span> id = 50;</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'>    <span class='keyword'>public</span> <span class='type'>int</span> number = 30;</div></div><div class='code-line'><span class='line-number'>6</span><div class='code'>    <span class='keyword'>public</span> student(<span class='type'>int</span> id, <span class='type'>int</span> number) {</div></div><div class='code-line'><span class='line-number'>7</span><div class='code'>        id = 10;</div></div><div class='code-line'><span class='line-number'>8</span><div class='code'>        number = 100;</div></div><div class='code-line'><span class='line-number'>9</span><div class='code'>    }</div></div><div class='code-line'><span class='line-number'>10</span><div class='code'>}</div></div></div></div>", options:["50","10","null","error"], correct:3, translate:"ما الناتج؟", explain:"خطأ: لا يوجد Constructor بدون parameters." },
      { id:2, text:"If a class defines no constructor, the compiler automatically creates a", options:["default","static","parameterized","copy"], correct:0, translate:"إذا لم يعرف الكلاس Constructor، فالمترجم ينشئ تلقائيًا", explain:"Default constructor (parameter-less)." },
      { id:3, text:"A constructor in C# has no return type", options:["True","False"], correct:0, translate:"الـ Constructor في C# ليس له نوع إرجاع", explain:"True" },
      { id:4, text:"Static class cannot have a constructor", options:["True","False"], correct:0, translate:"الـ static class لا يمكن أن يحتوي على Constructor", explain:"True (لا يمكن أن يكون له instances)" },
      { id:5, text:"Constructors are called when an object is", options:["destroyed","created","inherited","removed"], correct:1, translate:"الـ Constructor يُستدعى عندما يتم", explain:"عند إنشاء الكائن." },
      { id:6, text:"Which keyword refers to the current object?", options:["this","self","current","my"], correct:0, translate:"أي keyword يشير إلى الكائن الحالي؟", explain:"this" },
      { id:7, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>student</span> s1 = <span class='keyword'>new</span> <span class='type'>student</span>(100);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>Console.WriteLine(s1.id);</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'><span class='keyword'>class</span> <span class='type'>student</span> {</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>    <span class='keyword'>public</span> <span class='type'>int</span> id = 50;</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'>    <span class='keyword'>public</span> student(<span class='type'>int</span> id) { id = id; }</div></div><div class='code-line'><span class='line-number'>6</span><div class='code'>}</div></div></div></div>", options:["50","100","null","error"], correct:0, translate:"ما الناتج؟", explain:"المتغير المحلي id يخفي الحقل id، لم نستخدم this، فالحقل لم يتغير ويبقى 50." },
      { id:8, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>public</span> student(<span class='type'>int</span> id) { <span class='keyword'>this</span>.id = id; }</div></div></div></div>", options:["50","100","null","error"], correct:1, translate:"ما الناتج؟", explain:"this.id يشير للحقل، فتتغير قيمته إلى 100." },
      { id:9, text:"To access the class field when a parameter has the same name we use", options:["self",".","this",":"], correct:2, translate:"للوصول إلى حقل الكلاس عندما يكون الـ parameter بنفس الاسم نستخدم", explain:"this" },
      { id:10, text:"Constructors cannot be overloaded", options:["True","False"], correct:1, translate:"الـ Constructors لا يمكن عمل overloading لهم", explain:"False (يمكن overloading)" },
      { id:11, text:"Objects that are no longer used are removed from memory by", options:["delete operator","garbage collector","destructor","Amr Essam"], correct:1, translate:"الكائنات التي لم تعد مستخدمة تُحذف من الذاكرة بواسطة", explain:"Garbage Collector" },
      { id:12, text:"A destructor in C# begins with the symbol", options:[".","~","this",":"], correct:1, translate:"الـ Destructor في C# يبدأ بالرمز", explain:"~" },
      { id:13, text:"A class can have ______ constructors and ______ destructor.", options:["one, multi","multi, one","one, one","multi, multi"], correct:1, translate:"الكلاس يمكن أن يحتوي على ______ Constructor و ______ Destructor.", explain:"Multi constructors, one destructor" },
      { id:14, text:"When constructor parameter has the same name as a field, this is called", options:["overridden","shadowed","overloaded","none"], correct:1, translate:"عندما يكون اسم Parameter Constructor مطابقًا لاسم حقل، هذا يسمى", explain:"Shadowed (مخفي)" },
      { id:15, text:"A parameterised constructor is useful because it allows you to", options:["set initial values","enable multiple inheritance","call another constructor","delete memory"], correct:0, translate:"الـ Parameterised Constructor مفيد لأنه يسمح لك بـ", explain:"تعيين القيم الأولية." },
      { id:16, text:"Constructor overloading gives a class the flexibility to", options:["initialize objects in several ways","delete objects automatically","grant direct access to static fields","create only one type of object"], correct:0, translate:"Constructor Overloading يعطي الكلاس المرونة لـ", explain:"تهيئة الكائنات بعدة طرق." },
      { id:17, text:"A constructor is always given the same name as", options:["class","object","method","function"], correct:0, translate:"الـ Constructor دائمًا يُعطى نفس اسم", explain:"الكلاس" },
      { id:18, text:"Unlike regular methods, a constructor cannot declare (select 2)", options:["void","return","access modifier","static"], correct:[0,1], translate:"على عكس الدوال العادية، الـ Constructor لا يمكن أن يصرح بـ (اختر 2)", explain:"لا يمكن أن يكون له return type (ولا void) ولا return." },
      { id:19, text:"A constructor can call another constructor using", options:["this","call","new","~"], correct:0, translate:"الـ Constructor يمكنه استدعاء Constructor آخر باستخدام", explain:"this()" }
    ]
  },
  {
    id: 4,
    title: "Chapter 4 | Objects, Methods, Arrays",
    questions: [
      { id:1, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>student</span> x = <span class='keyword'>new</span> <span class='type'>student</span>(<span class='string'>\"aa\"</span>);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='keyword'>ref</span> <span class='type'>student</span> y = <span class='keyword'>ref</span> x;</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>y = <span class='keyword'>new</span> <span class='type'>student</span>(<span class='string'>\"qq\"</span>);</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>Console.WriteLine(x.courses);</div></div></div></div>", options:["aa","qq","null","error"], correct:1, translate:"ما الناتج؟", explain:"ref يمرر المرجع نفسه، تغيير y يغير x." },
      { id:2, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>student</span> x = <span class='keyword'>new</span> <span class='type'>student</span>(<span class='string'>\"aa\"</span>);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='type'>student</span> y = x;</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>y = <span class='keyword'>new</span> <span class='type'>student</span>(<span class='string'>\"qq\"</span>);</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>Console.WriteLine(x.courses);</div></div></div></div>", options:["aa","qq","null","error"], correct:0, translate:"ما الناتج؟", explain:"y نسخة من المرجع، تغيير y لا يؤثر على x." },
      { id:3, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Student</span> x = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"Adam\"</span>, 60);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='type'>Student</span> y = x;</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>y.score = 100;</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>Console.WriteLine(x.score);</div></div></div></div>", options:["60","100","null","error"], correct:1, translate:"ما الناتج؟", explain:"y و x يشيران لنفس الكائن، تغيير score يظهر في كليهما." },
      { id:4, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Student</span> x = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"A\"</span>, 10);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='type'>Student</span> y = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"B\"</span>, 20);</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>y = x;</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>y.score = 99;</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'>Console.WriteLine(x.score);</div></div></div></div>", options:["10","20","99","error"], correct:2, translate:"ما الناتج؟", explain:"بعد y = x، يشيران لنفس الكائن، تغيير score = 99 يؤثر على x." },
      { id:5, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Student</span> x = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"A\"</span>, 10);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>Modify(x);</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>Console.WriteLine(x.score);</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'><span class='keyword'>void</span> <span class='function'>Modify</span>(<span class='type'>Student</span> s) {</div></div><div class='code-line'><span class='line-number'>5</span><div class='code'>    s = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"B\"</span>, 50);</div></div><div class='code-line'><span class='line-number'>6</span><div class='code'>}</div></div></div></div>", options:["10","50","0","error"], correct:0, translate:"ما الناتج؟", explain:"تمرير reference by value (النسخة) تغيير s لا يؤثر على x." },
      { id:6, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'>Modify(<span class='keyword'>ref</span> x);</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='keyword'>void</span> <span class='function'>Modify</span>(<span class='keyword'>ref</span> <span class='type'>Student</span> s) {</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>    s = <span class='keyword'>new</span> <span class='type'>Student</span>(<span class='string'>\"B\"</span>, 50);</div></div><div class='code-line'><span class='line-number'>4</span><div class='code'>}</div></div></div></div>", options:["10","50","0","error"], correct:1, translate:"ما الناتج؟", explain:"ref يمرر المرجع نفسه، تغيير s يغير x." },
      { id:7, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='keyword'>class</span> <span class='type'>student</span> { <span class='keyword'>public</span> <span class='type'>string</span> name; <span class='keyword'>public</span> <span class='type'>int</span> id; <span class='keyword'>public</span> <span class='type'>double</span> GPA; }</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'><span class='type'>student</span>[] std = <span class='keyword'>new</span> <span class='type'>student</span>[3];</div></div><div class='code-line'><span class='line-number'>3</span><div class='code'>Console.WriteLine(std[1]);</div></div></div></div>", options:["object address","0","null","error"], correct:2, translate:"ما الناتج؟", explain:"مصفوفة من reference types، العناصر لم تنشأ بعد فالقيمة null." },
      { id:8, text:"<div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'>std[1].name = <span class='string'>\"Adam\"</span>;</div></div><div class='code-line'><span class='line-number'>2</span><div class='code'>Console.WriteLine(std[1].name);</div></div></div></div>", options:["Adam","Amr","null","error"], correct:3, translate:"ما الناتج؟", explain:"std[1] = null، لا يمكن الوصول لـ name." },
      { id:9, text:"How many Student objects exist after: <div class='code-editor'><div class='editor-header'><div class='window-buttons'><span class='close'></span><span class='minimize'></span><span class='maximize'></span></div><div class='editor-info'>C#</div></div><div class='editor-content'><div class='code-line'><span class='line-number'>1</span><div class='code'><span class='type'>Student</span>[] students = <span class='keyword'>new</span> <span class='type'>Student</span>[3];</div></div></div></div>", options:["3","0","1","error"], correct:1, translate:"كم عدد كائنات Student الموجودة؟", explain:"0، تم إنشاء المصفوفة فقط، لا توجد كائنات Student." },
      { id:10, text:"In C#, passing parameters by value means", options:["original variable is modified","a copy of the variable is passed","memory is duplicated","reference is destroyed"], correct:1, translate:"تمرير المعاملات by value في C# يعني", explain:"يتم تمرير نسخة من المتغير." },
      { id:11, text:"When passing a reference-type variable to a method by value,", options:["object is copied","nothing is copied","both object & ref are copied","reference is copied"], correct:3, translate:"عند تمرير متغير reference-type إلى method by value،", explain:"يتم نسخ المرجع (العنوان) وليس الكائن نفسه." },
      { id:12, text:"What does the ref keyword do when used with a reference-type parameter?", options:["makes a copy of object","passes the ref variable itself","works same as passing without ref","prevents modification"], correct:1, translate:"ماذا يفعل ref مع parameter من type reference؟", explain:"يمرر المتغير المرجع نفسه (الموقع في الذاكرة)." },
      { id:13, text:"How many params can a single method have?", options:["Unlimited","0","1","2"], correct:2, translate:"كم عدد params التي يمكن أن تحتويها دالة واحدة؟", explain:"يمكن أن يكون هناك params واحد فقط في التوقيع." },
      { id:14, text:"Which modifier allows a method to accept a variable number of arguments?", options:["class","array","params","var"], correct:2, translate:"أي modifier يسمح للدالة باستقبال عدد متغير من المعاملات؟", explain:"params" },
      { id:15, text:"When you create an array of value type (e.g., int), each slot stores", options:["references to heap objects","actual data","object itself","money"], correct:1, translate:"عند إنشاء مصفوفة من value type، كل خانة تخزن", explain:"البيانات الفعلية (actual data)." },
      { id:16, text:"An array whose element type is a reference type stores in each slot", options:["actual values","set of references","set of nulls","set of drags"], correct:1, translate:"المصفوفة التي عناصرها reference type تخزن في كل خانة", explain:"مراجع (references) للكائنات في Heap." }
    ]
  },
  {
    id: 5,
    title: "Chapter 5 | Properties & Indexers",
    questions: [
      { id:1, text:"A property is a class member that offers a controlled way to read or write a", options:["public field","private field","static field","base field"], correct:1, translate:"الـ property هو عضو في الكلاس يوفر طريقة محكمة لقراءة أو كتابة", explain:"الـ property يتحكم في الوصول إلى private field." },
      { id:2, text:"How many accessors can a property have?", options:["0","1","2","3"], correct:2, translate:"كم accessor يمكن أن يملك الـ property؟", explain:"get و set فقط." },
      { id:3, text:"Which accessor is responsible for reading and returning the current value?", options:["get","set","value","return"], correct:0, translate:"أي accessor مسؤول عن قراءة وإرجاع القيمة الحالية؟", explain:"get" },
      { id:4, text:"Which accessor is used to assign a new value to the underlying private field?", options:["get","set","value","return"], correct:1, translate:"أي accessor يستخدم لتعيين قيمة جديدة للحقل الخاص؟", explain:"set" },
      { id:5, text:"Inside set accessor, which keyword holds the value being assigned?", options:["get","set","value","return"], correct:2, translate:"داخل set accessor، أي keyword يحمل القيمة المعينة؟", explain:"value" },
      { id:6, text:"To make a property read-only, you should include only the accessor", options:["get","set","value","return"], correct:0, translate:"لجعل property للقراءة فقط، يجب تضمين accessor فقط", explain:"get فقط." },
      { id:7, text:"A write-only property is characterized by having", options:["get only","set only (or private get)","both","none"], correct:1, translate:"الـ write-only property يتميز بوجود", explain:"set فقط (أو get خاص)." },
      { id:8, text:"Which feature allows objects to be accessed like an array?", options:["properties","indexer","methods","fields"], correct:1, translate:"أي ميزة تسمح بالوصول إلى الكائنات مثل المصفوفة؟", explain:"indexer" },
      { id:9, text:"The primary purpose of an indexer is to enable", options:["deleting fields","overloading class definitions","array-like access","overriding objects"], correct:2, translate:"الغرض الأساسي من indexer هو تمكين", explain:"الوصول الشبيه بالمصفوفة." },
      { id:10, text:"Indexers are similar to properties but their accessors", options:["take parameters","take no parameters","return value","do not return value"], correct:0, translate:"Indexers تشبه properties لكن accessors الخاصة بها", explain:"تأخذ parameters (مفتاح الوصول)." },
      { id:11, text:"Indexers can take zero or more parameters", options:["True","False"], correct:1, translate:"Indexers يمكن أن تأخذ صفر أو أكثر من parameters", explain:"False، يجب أن تأخذ parameter واحد على الأقل." },
      { id:12, text:"In automatic property, you don't create a private field because the compiler creates a", options:["hidden backing field","auto static field","public field","koshary"], correct:0, translate:"في automatic property، لا تنشئ private field لأن المترجم ينشئ", explain:"hidden backing field." },
      { id:13, text:"Indexers can be", options:["overloaded","named","fly","overqualified"], correct:0, translate:"Indexers يمكن أن تكون", explain:"overloaded (محملة بشكل زائد)." },
      { id:14, text:"Indexers use what keyword in their name?", options:["class name","this","object name","any name"], correct:1, translate:"Indexers تستخدم أي keyword في اسمها؟", explain:"this" }
    ]
  },
  {
    id: 6,
    title: "Chapter 6 | Operator Overloading",
    questions: [
      { id:1, text:"Placeholder: Add Operator Overloading questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Operator Overloading هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:2, text:"Placeholder: Add Operator Overloading questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Operator Overloading هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:3, text:"Placeholder: Add Operator Overloading questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Operator Overloading هنا", explain:"يتم إضافة الأسئلة لاحقًا" }
    ]
  },
  {
    id: 7,
    title: "Chapter 7 | Inheritance",
    questions: [
      { id:1, text:"Placeholder: Add Inheritance questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Inheritance هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:2, text:"Placeholder: Add Inheritance questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Inheritance هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:3, text:"Placeholder: Add Inheritance questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Inheritance هنا", explain:"يتم إضافة الأسئلة لاحقًا" }
    ]
  },
  {
    id: 8,
    title: "Chapter 8 | Polymorphism & Interfaces",
    questions: [
      { id:1, text:"Placeholder: Add Polymorphism & Interfaces questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Polymorphism & Interfaces هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:2, text:"Placeholder: Add Polymorphism & Interfaces questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Polymorphism & Interfaces هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:3, text:"Placeholder: Add Polymorphism & Interfaces questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة Polymorphism & Interfaces هنا", explain:"يتم إضافة الأسئلة لاحقًا" }
    ]
  },
  {
    id: 9,
    title: "Chapters 9–10 | UML, Enums, Structs",
    questions: [
      { id:1, text:"Placeholder: Add UML, Enums, Structs questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة UML, Enums, Structs هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:2, text:"Placeholder: Add UML, Enums, Structs questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة UML, Enums, Structs هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:3, text:"Placeholder: Add UML, Enums, Structs questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة UML, Enums, Structs هنا", explain:"يتم إضافة الأسئلة لاحقًا" }
    ]
  },
  {
    id: 10,
    title: "Chapters 11–14 | Delegates, Events, Files, Exceptions, GUI",
    questions: [
      { id:1, text:"Placeholder: Add Delegates, Events, Files, Exceptions, GUI questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة آخر 4 فصول هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:2, text:"Placeholder: Add Delegates, Events, Files, Exceptions, GUI questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة آخر 4 فصول هنا", explain:"يتم إضافة الأسئلة لاحقًا" },
      { id:3, text:"Placeholder: Add Delegates, Events, Files, Exceptions, GUI questions here", options:["A","B","C","D"], correct:0, translate:"أضف أسئلة آخر 4 فصول هنا", explain:"يتم إضافة الأسئلة لاحقًا" }
    ]
  }
];